### ISSUE TITLE
feat #3 : 두 개의 숫자를 비교하는 기능

### ISSUE THREAD

**Issue by EungyuHan** [EungyuHan/java-baseball-6#3]
- [ ] feat #3-1 : 숫자와 자리가 모두 일치하는 경우
- [ ] feat #3-2 : 숫자만 일치하는 경우
- [ ] feat #3-3 : 일치하는 숫자가 없는 경우
- [ ] feat #3-4 : 조건에 맞는 힌트를 출력하는 기능
